### ISSUE TITLE
System should provide an at-a-glance display of the cash amount available by denomination

### ISSUE THREAD

**Issue by santhoshiss** [Project-Team-FT1/vmcs-before#1]
Enhancement to be implemented as per Change Request ticket number: VMCS-CR-01

**Comment by abhinaviss** [comment]
Implemented enhancement as per Change Request ticket number VMCS-CR-01. Please test and confirm.

**Comment by santhoshiss** [comment]
Enhancement working fine. Please confirm after UAT.

**Comment by lijixiangiss** [comment]
Enhancement working fine. Thanks.
