### ISSUE TITLE
Reset values to null when Maintainer successfully pushes "Press Here When Finished"

### ISSUE THREAD

**Issue by santhoshiss** [Project-Team-FT1/vmcs-before#2]
Severity 2 bug to be resolved as part of Change Request ticket number VMCS-CR-02

**Comment by abhinaviss** [comment]
Resolved severity 2 bug as per Change Request ticket number VMCS-CR-02. Please retest and confirm.

**Comment by santhoshiss** [comment]
Issue fixed. Please confirm after UAT.

**Comment by lijixiangiss** [comment]
Issue fixed and working fine.Thanks.
